packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: true

catalog:
  better-auth: ^1.7.6
  dotenv: ^18.0.5
  "@effect/sql-pg": 4.0.0
  "@effect/vitest": 4.0.0
  "@types/pg": 8.23.1
  drizzle-kit: 1.0.0-rc.5-5935859
  drizzle-orm: 1.0.0-rc.5-5935859
  effect: 4.0.0
  hono: ^4.13.12
  pg: 8.23.0
  typescript: 7.0.2
  vitest: ^5.0.3
  zod: ^4.6.5
  linkedom: ^0.18.13

minimumReleaseAgeExclude:
  - cn@0.2.4
  - "@vitest/mocker@5.0.0"
  - "@vitest/spy@5.0.0"
  - vitest@5.0.0
  - "@effect/platform-node-shared@4.0.0"
  - "@effect/platform-node@4.0.0"
  - "@effect/sql-pg@4.0.0"
  - "@effect/vitest@4.0.0"
  - effect@4.0.0

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract

patchedDependencies:
  drizzle-orm@1.0.0-rc.5-5935859: patches/drizzle-orm@1.0.0-rc.5-5935859.patch
