packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.13.5
  '@orpc/openapi': ^1.13.5
  '@orpc/server': ^1.13.5
  '@orpc/zod': ^1.13.5
  better-auth: ^1.4.19
  dotenv: ^17.3.1
  drizzle-orm: ^0.44.7
  hono: ^4.12.2
  tsdown: ^0.15.12
  typescript: ^5.9.3
  zod: ^4.3.6

onlyBuiltDependencies:
  - esbuild
