/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingRoomRouteImport } from './routes/waiting-room'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPlayerListRouteImport } from './routes/dashboard/player-list'
import { Route as DashboardSkillsRouteRouteImport } from './routes/dashboard/skills/route'
import { Route as DashboardAuctionsRouteRouteImport } from './routes/dashboard/auctions/route'
import { Route as DashboardSkillsIndexRouteImport } from './routes/dashboard/skills/index'
import { Route as DashboardSkillsRangeNameRouteImport } from './routes/dashboard/skills/$rangeName'
import { Route as DashboardEventsVaultRouteImport } from './routes/dashboard/events/vault'
import { Route as DashboardEventsRankingRouteImport } from './routes/dashboard/events/ranking'
import { Route as DashboardEventsMapsRouteImport } from './routes/dashboard/events/maps'
import { Route as DashboardEventsListRouteImport } from './routes/dashboard/events/list'
import { Route as DashboardEventsHistoryRouteImport } from './routes/dashboard/events/history'
import { Route as DashboardEventsHeroesRouteImport } from './routes/dashboard/events/heroes'
import { Route as DashboardCalculatorUlepaRouteImport } from './routes/dashboard/calculator/ulepa'
import { Route as DashboardCalculatorOdwRouteImport } from './routes/dashboard/calculator/odw'
import { Route as DashboardCalculatorListRouteImport } from './routes/dashboard/calculator/list'
import { Route as DashboardAuctionsTypeRouteRouteImport } from './routes/dashboard/auctions/$type/route'
import { Route as DashboardAuctionsTypeIndexRouteImport } from './routes/dashboard/auctions/$type/index'
import { Route as DashboardEventsBetsAddRouteImport } from './routes/dashboard/events/bets.add'
import { Route as DashboardAuctionsTypeProfessionRouteImport } from './routes/dashboard/auctions/$type/$profession'

const WaitingRoomRoute = WaitingRoomRouteImport.update({
  id: '/waiting-room',
  path: '/waiting-room',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayerListRoute = DashboardPlayerListRouteImport.update({
  id: '/player-list',
  path: '/player-list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSkillsRouteRoute = DashboardSkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuctionsRouteRoute = DashboardAuctionsRouteRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSkillsIndexRoute = DashboardSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSkillsRouteRoute,
} as any)
const DashboardSkillsRangeNameRoute =
  DashboardSkillsRangeNameRouteImport.update({
    id: '/$rangeName',
    path: '/$rangeName',
    getParentRoute: () => DashboardSkillsRouteRoute,
  } as any)
const DashboardEventsVaultRoute = DashboardEventsVaultRouteImport.update({
  id: '/events/vault',
  path: '/events/vault',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRankingRoute = DashboardEventsRankingRouteImport.update({
  id: '/events/ranking',
  path: '/events/ranking',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsMapsRoute = DashboardEventsMapsRouteImport.update({
  id: '/events/maps',
  path: '/events/maps',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsListRoute = DashboardEventsListRouteImport.update({
  id: '/events/list',
  path: '/events/list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsHistoryRoute = DashboardEventsHistoryRouteImport.update({
  id: '/events/history',
  path: '/events/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsHeroesRoute = DashboardEventsHeroesRouteImport.update({
  id: '/events/heroes',
  path: '/events/heroes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalculatorUlepaRoute =
  DashboardCalculatorUlepaRouteImport.update({
    id: '/calculator/ulepa',
    path: '/calculator/ulepa',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCalculatorOdwRoute = DashboardCalculatorOdwRouteImport.update({
  id: '/calculator/odw',
  path: '/calculator/odw',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalculatorListRoute = DashboardCalculatorListRouteImport.update({
  id: '/calculator/list',
  path: '/calculator/list',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuctionsTypeRouteRoute =
  DashboardAuctionsTypeRouteRouteImport.update({
    id: '/$type',
    path: '/$type',
    getParentRoute: () => DashboardAuctionsRouteRoute,
  } as any)
const DashboardAuctionsTypeIndexRoute =
  DashboardAuctionsTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuctionsTypeRouteRoute,
  } as any)
const DashboardEventsBetsAddRoute = DashboardEventsBetsAddRouteImport.update({
  id: '/events/bets/add',
  path: '/events/bets/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAuctionsTypeProfessionRoute =
  DashboardAuctionsTypeProfessionRouteImport.update({
    id: '/$profession',
    path: '/$profession',
    getParentRoute: () => DashboardAuctionsTypeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRouteRouteWithChildren
  '/dashboard/player-list': typeof DashboardPlayerListRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auctions/$type': typeof DashboardAuctionsTypeRouteRouteWithChildren
  '/dashboard/calculator/list': typeof DashboardCalculatorListRoute
  '/dashboard/calculator/odw': typeof DashboardCalculatorOdwRoute
  '/dashboard/calculator/ulepa': typeof DashboardCalculatorUlepaRoute
  '/dashboard/events/heroes': typeof DashboardEventsHeroesRoute
  '/dashboard/events/history': typeof DashboardEventsHistoryRoute
  '/dashboard/events/list': typeof DashboardEventsListRoute
  '/dashboard/events/maps': typeof DashboardEventsMapsRoute
  '/dashboard/events/ranking': typeof DashboardEventsRankingRoute
  '/dashboard/events/vault': typeof DashboardEventsVaultRoute
  '/dashboard/skills/$rangeName': typeof DashboardSkillsRangeNameRoute
  '/dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/dashboard/auctions/$type/$profession': typeof DashboardAuctionsTypeProfessionRoute
  '/dashboard/events/bets/add': typeof DashboardEventsBetsAddRoute
  '/dashboard/auctions/$type/': typeof DashboardAuctionsTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteRouteWithChildren
  '/dashboard/player-list': typeof DashboardPlayerListRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/calculator/list': typeof DashboardCalculatorListRoute
  '/dashboard/calculator/odw': typeof DashboardCalculatorOdwRoute
  '/dashboard/calculator/ulepa': typeof DashboardCalculatorUlepaRoute
  '/dashboard/events/heroes': typeof DashboardEventsHeroesRoute
  '/dashboard/events/history': typeof DashboardEventsHistoryRoute
  '/dashboard/events/list': typeof DashboardEventsListRoute
  '/dashboard/events/maps': typeof DashboardEventsMapsRoute
  '/dashboard/events/ranking': typeof DashboardEventsRankingRoute
  '/dashboard/events/vault': typeof DashboardEventsVaultRoute
  '/dashboard/skills/$rangeName': typeof DashboardSkillsRangeNameRoute
  '/dashboard/skills': typeof DashboardSkillsIndexRoute
  '/dashboard/auctions/$type/$profession': typeof DashboardAuctionsTypeProfessionRoute
  '/dashboard/events/bets/add': typeof DashboardEventsBetsAddRoute
  '/dashboard/auctions/$type': typeof DashboardAuctionsTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/dashboard/auctions': typeof DashboardAuctionsRouteRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRouteRouteWithChildren
  '/dashboard/player-list': typeof DashboardPlayerListRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/auctions/$type': typeof DashboardAuctionsTypeRouteRouteWithChildren
  '/dashboard/calculator/list': typeof DashboardCalculatorListRoute
  '/dashboard/calculator/odw': typeof DashboardCalculatorOdwRoute
  '/dashboard/calculator/ulepa': typeof DashboardCalculatorUlepaRoute
  '/dashboard/events/heroes': typeof DashboardEventsHeroesRoute
  '/dashboard/events/history': typeof DashboardEventsHistoryRoute
  '/dashboard/events/list': typeof DashboardEventsListRoute
  '/dashboard/events/maps': typeof DashboardEventsMapsRoute
  '/dashboard/events/ranking': typeof DashboardEventsRankingRoute
  '/dashboard/events/vault': typeof DashboardEventsVaultRoute
  '/dashboard/skills/$rangeName': typeof DashboardSkillsRangeNameRoute
  '/dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/dashboard/auctions/$type/$profession': typeof DashboardAuctionsTypeProfessionRoute
  '/dashboard/events/bets/add': typeof DashboardEventsBetsAddRoute
  '/dashboard/auctions/$type/': typeof DashboardAuctionsTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/waiting-room'
    | '/dashboard/auctions'
    | '/dashboard/skills'
    | '/dashboard/player-list'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/auctions/$type'
    | '/dashboard/calculator/list'
    | '/dashboard/calculator/odw'
    | '/dashboard/calculator/ulepa'
    | '/dashboard/events/heroes'
    | '/dashboard/events/history'
    | '/dashboard/events/list'
    | '/dashboard/events/maps'
    | '/dashboard/events/ranking'
    | '/dashboard/events/vault'
    | '/dashboard/skills/$rangeName'
    | '/dashboard/skills/'
    | '/dashboard/auctions/$type/$profession'
    | '/dashboard/events/bets/add'
    | '/dashboard/auctions/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/waiting-room'
    | '/dashboard/auctions'
    | '/dashboard/player-list'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/calculator/list'
    | '/dashboard/calculator/odw'
    | '/dashboard/calculator/ulepa'
    | '/dashboard/events/heroes'
    | '/dashboard/events/history'
    | '/dashboard/events/list'
    | '/dashboard/events/maps'
    | '/dashboard/events/ranking'
    | '/dashboard/events/vault'
    | '/dashboard/skills/$rangeName'
    | '/dashboard/skills'
    | '/dashboard/auctions/$type/$profession'
    | '/dashboard/events/bets/add'
    | '/dashboard/auctions/$type'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/waiting-room'
    | '/dashboard/auctions'
    | '/dashboard/skills'
    | '/dashboard/player-list'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/auctions/$type'
    | '/dashboard/calculator/list'
    | '/dashboard/calculator/odw'
    | '/dashboard/calculator/ulepa'
    | '/dashboard/events/heroes'
    | '/dashboard/events/history'
    | '/dashboard/events/list'
    | '/dashboard/events/maps'
    | '/dashboard/events/ranking'
    | '/dashboard/events/vault'
    | '/dashboard/skills/$rangeName'
    | '/dashboard/skills/'
    | '/dashboard/auctions/$type/$profession'
    | '/dashboard/events/bets/add'
    | '/dashboard/auctions/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WaitingRoomRoute: typeof WaitingRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-room': {
      id: '/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof WaitingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/player-list': {
      id: '/dashboard/player-list'
      path: '/player-list'
      fullPath: '/dashboard/player-list'
      preLoaderRoute: typeof DashboardPlayerListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auctions': {
      id: '/dashboard/auctions'
      path: '/auctions'
      fullPath: '/dashboard/auctions'
      preLoaderRoute: typeof DashboardAuctionsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/skills/': {
      id: '/dashboard/skills/'
      path: '/'
      fullPath: '/dashboard/skills/'
      preLoaderRoute: typeof DashboardSkillsIndexRouteImport
      parentRoute: typeof DashboardSkillsRouteRoute
    }
    '/dashboard/skills/$rangeName': {
      id: '/dashboard/skills/$rangeName'
      path: '/$rangeName'
      fullPath: '/dashboard/skills/$rangeName'
      preLoaderRoute: typeof DashboardSkillsRangeNameRouteImport
      parentRoute: typeof DashboardSkillsRouteRoute
    }
    '/dashboard/events/vault': {
      id: '/dashboard/events/vault'
      path: '/events/vault'
      fullPath: '/dashboard/events/vault'
      preLoaderRoute: typeof DashboardEventsVaultRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/ranking': {
      id: '/dashboard/events/ranking'
      path: '/events/ranking'
      fullPath: '/dashboard/events/ranking'
      preLoaderRoute: typeof DashboardEventsRankingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/maps': {
      id: '/dashboard/events/maps'
      path: '/events/maps'
      fullPath: '/dashboard/events/maps'
      preLoaderRoute: typeof DashboardEventsMapsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/list': {
      id: '/dashboard/events/list'
      path: '/events/list'
      fullPath: '/dashboard/events/list'
      preLoaderRoute: typeof DashboardEventsListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/history': {
      id: '/dashboard/events/history'
      path: '/events/history'
      fullPath: '/dashboard/events/history'
      preLoaderRoute: typeof DashboardEventsHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events/heroes': {
      id: '/dashboard/events/heroes'
      path: '/events/heroes'
      fullPath: '/dashboard/events/heroes'
      preLoaderRoute: typeof DashboardEventsHeroesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculator/ulepa': {
      id: '/dashboard/calculator/ulepa'
      path: '/calculator/ulepa'
      fullPath: '/dashboard/calculator/ulepa'
      preLoaderRoute: typeof DashboardCalculatorUlepaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculator/odw': {
      id: '/dashboard/calculator/odw'
      path: '/calculator/odw'
      fullPath: '/dashboard/calculator/odw'
      preLoaderRoute: typeof DashboardCalculatorOdwRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calculator/list': {
      id: '/dashboard/calculator/list'
      path: '/calculator/list'
      fullPath: '/dashboard/calculator/list'
      preLoaderRoute: typeof DashboardCalculatorListRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auctions/$type': {
      id: '/dashboard/auctions/$type'
      path: '/$type'
      fullPath: '/dashboard/auctions/$type'
      preLoaderRoute: typeof DashboardAuctionsTypeRouteRouteImport
      parentRoute: typeof DashboardAuctionsRouteRoute
    }
    '/dashboard/auctions/$type/': {
      id: '/dashboard/auctions/$type/'
      path: '/'
      fullPath: '/dashboard/auctions/$type/'
      preLoaderRoute: typeof DashboardAuctionsTypeIndexRouteImport
      parentRoute: typeof DashboardAuctionsTypeRouteRoute
    }
    '/dashboard/events/bets/add': {
      id: '/dashboard/events/bets/add'
      path: '/events/bets/add'
      fullPath: '/dashboard/events/bets/add'
      preLoaderRoute: typeof DashboardEventsBetsAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/auctions/$type/$profession': {
      id: '/dashboard/auctions/$type/$profession'
      path: '/$profession'
      fullPath: '/dashboard/auctions/$type/$profession'
      preLoaderRoute: typeof DashboardAuctionsTypeProfessionRouteImport
      parentRoute: typeof DashboardAuctionsTypeRouteRoute
    }
  }
}

interface DashboardAuctionsTypeRouteRouteChildren {
  DashboardAuctionsTypeProfessionRoute: typeof DashboardAuctionsTypeProfessionRoute
  DashboardAuctionsTypeIndexRoute: typeof DashboardAuctionsTypeIndexRoute
}

const DashboardAuctionsTypeRouteRouteChildren: DashboardAuctionsTypeRouteRouteChildren =
  {
    DashboardAuctionsTypeProfessionRoute: DashboardAuctionsTypeProfessionRoute,
    DashboardAuctionsTypeIndexRoute: DashboardAuctionsTypeIndexRoute,
  }

const DashboardAuctionsTypeRouteRouteWithChildren =
  DashboardAuctionsTypeRouteRoute._addFileChildren(
    DashboardAuctionsTypeRouteRouteChildren,
  )

interface DashboardAuctionsRouteRouteChildren {
  DashboardAuctionsTypeRouteRoute: typeof DashboardAuctionsTypeRouteRouteWithChildren
}

const DashboardAuctionsRouteRouteChildren: DashboardAuctionsRouteRouteChildren =
  {
    DashboardAuctionsTypeRouteRoute:
      DashboardAuctionsTypeRouteRouteWithChildren,
  }

const DashboardAuctionsRouteRouteWithChildren =
  DashboardAuctionsRouteRoute._addFileChildren(
    DashboardAuctionsRouteRouteChildren,
  )

interface DashboardSkillsRouteRouteChildren {
  DashboardSkillsRangeNameRoute: typeof DashboardSkillsRangeNameRoute
  DashboardSkillsIndexRoute: typeof DashboardSkillsIndexRoute
}

const DashboardSkillsRouteRouteChildren: DashboardSkillsRouteRouteChildren = {
  DashboardSkillsRangeNameRoute: DashboardSkillsRangeNameRoute,
  DashboardSkillsIndexRoute: DashboardSkillsIndexRoute,
}

const DashboardSkillsRouteRouteWithChildren =
  DashboardSkillsRouteRoute._addFileChildren(DashboardSkillsRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAuctionsRouteRoute: typeof DashboardAuctionsRouteRouteWithChildren
  DashboardSkillsRouteRoute: typeof DashboardSkillsRouteRouteWithChildren
  DashboardPlayerListRoute: typeof DashboardPlayerListRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCalculatorListRoute: typeof DashboardCalculatorListRoute
  DashboardCalculatorOdwRoute: typeof DashboardCalculatorOdwRoute
  DashboardCalculatorUlepaRoute: typeof DashboardCalculatorUlepaRoute
  DashboardEventsHeroesRoute: typeof DashboardEventsHeroesRoute
  DashboardEventsHistoryRoute: typeof DashboardEventsHistoryRoute
  DashboardEventsListRoute: typeof DashboardEventsListRoute
  DashboardEventsMapsRoute: typeof DashboardEventsMapsRoute
  DashboardEventsRankingRoute: typeof DashboardEventsRankingRoute
  DashboardEventsVaultRoute: typeof DashboardEventsVaultRoute
  DashboardEventsBetsAddRoute: typeof DashboardEventsBetsAddRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAuctionsRouteRoute: DashboardAuctionsRouteRouteWithChildren,
  DashboardSkillsRouteRoute: DashboardSkillsRouteRouteWithChildren,
  DashboardPlayerListRoute: DashboardPlayerListRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCalculatorListRoute: DashboardCalculatorListRoute,
  DashboardCalculatorOdwRoute: DashboardCalculatorOdwRoute,
  DashboardCalculatorUlepaRoute: DashboardCalculatorUlepaRoute,
  DashboardEventsHeroesRoute: DashboardEventsHeroesRoute,
  DashboardEventsHistoryRoute: DashboardEventsHistoryRoute,
  DashboardEventsListRoute: DashboardEventsListRoute,
  DashboardEventsMapsRoute: DashboardEventsMapsRoute,
  DashboardEventsRankingRoute: DashboardEventsRankingRoute,
  DashboardEventsVaultRoute: DashboardEventsVaultRoute,
  DashboardEventsBetsAddRoute: DashboardEventsBetsAddRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WaitingRoomRoute: WaitingRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
