import * as Schema from "effect/Schema";

export class EffectSquadBuilderPersistenceUnavailable extends Schema.TaggedErrorClass<EffectSquadBuilderPersistenceUnavailable>()(
  "SquadBuilderPersistenceUnavailable",
  {
    cause: Schema.Unknown,
    operation: Schema.Literals([
      "applyRefetchedAccount",
      "authorizeSquadGroupOwner",
      "createSquadGroup",
      "createOwnedAccountFromPendingImport",
      "createPendingImport",
      "createPendingRefetch",
      "findOwnedAccountForSharing",
      "findVerifiedInviteTarget",
      "findVerifiedSquadEditorInviteTarget",
      "findPendingImportForConfirmation",
      "findPendingRefetchForApply",
      "findProfileAccessState",
      "getAccountForRefetch",
      "getPendingSquadGroupInviteCount",
      "getSquadGroupDetail",
      "listAvailableCharactersForOwner",
      "listAccountAccessGrants",
      "listGlobalSquadGroups",
      "listIncomingAccountInvites",
      "listIncomingSquadGroupInvites",
      "listMySquadGroups",
      "listOwnedAccounts",
      "listSharedAccounts",
      "listSharedSquadGroups",
      "listSquadGroupEditorGrants",
      "markPendingRefetchApplied",
      "markRequestFailed",
      "markRequestSucceeded",
      "reserveRequest",
      "respondToAccountAccessInvite",
      "respondToSquadGroupInvite",
      "revokeAccountAccess",
      "revokeSquadGroupEditor",
      "saveSharedSquadGroupCharacters",
      "saveSquadGroupSnapshot",
      "searchSquadEditorInviteTargets",
      "searchInviteTargets",
      "setSquadGroupVisibility",
      "upsertAccountAccessInvite",
      "upsertSquadGroupEditorInvite",
    ]),
    provider: Schema.Literal("postgres"),
  }
) {}
